config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	resources :comments
  end 
  
  resources :posts do
  	resources :likes
  end

  resources :comments do
  	resources :likes
  end
  
  resources :friendships
  
  root 'dashboard#index'
  get 'welcome/index'
  # post 'friendships/index'
  # post 'friendships/create'
  # post 'friendships/update'
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes , as: :likeable
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User" 

  scope :pending_friends, -> (id) {where(friend_id: id)} 
  before_create :set_status
  # after_update :update_reverse_friendship

  private 
  def set_status
    self.status = 0 
  end


  # def update_reverse_friendship
    # reverse_friendship = Friendship.where(
    #   user_id: self.friend_id,
    #   friend_id: self.user_id
    # ).first
    
  #   reverse_friendship.update(status: 1) if reverse_friendship.present?
  # end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable ,polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable
  has_one_attached :file
  validates :post_mode,:caption, presence: true 
  validates :caption, length: { minimum: 5, maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :friendships 
  has_many :friends, :through => :friendships
  
  validates :username,:first_name,:last_name,:age, presence: true  
  validates :username, uniqueness: true, length: {minimum: 3}
  validates :age, numericality: true

  scope :new_friends, -> (fname) { includes(:friendships).where(first_name: fname) }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  
  def index
    @comment = @post.comments
  end
  def create
    @comment = @post.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.js      
        format.html { redirect_to root_path, notice: 'Commented.' } 
      end
    end
  end

  def destroy
    @comment = current_user.posts.find_by(id: params[:post_id]).comments.find_by(id: params[:id])
    respond_to do |format|
      if @comment.destroy
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  private
  def comment_params 
    params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find_by(id: params[:post_id])
  end
end 

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @post = Post.new
    if user_signed_in?
      @posts   = current_user.posts
      @friends = current_user.friendships.where(status: 1)
    else
      redirect_to welcome_index_path
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :find_friendship

  def index
    @users = User.new_friends(params[:user][:first_name])
    @pending = Friendship.pending_friends(current_user.id)
  end

  def create
    @friendship_user = current_user.friendships.new(friend_id: params[:friend_id])
    @friendship_friend  = User.find_by(id: params[:friend_id]).friendships.new(friend_id: current_user.id)
    if @friendship_user.save && @friendship_friend.save 
      redirect_to root_path
    else
      render plain: "You cannot send Friend Request"
    end
  end
  
  def update
    if @friendship.present? && @friendship.update(status: 1)
      update_reverse_friendship
      redirect_to root_path
    else
      render plain: "Already Friends"
    end
  end

  private

  def find_friendship
    @friendship = Friendship.find_by(id: params[:id])
  end

  def update_reverse_friendship
    reverse_friendship = Friendship.where(
      user_id: @friendship.friend_id,
      friend_id: @friendship.user_id
    ).first

    if reverse_friendship.present?
      reverse_friendship.update(status: 1)
    else 
      render plain: "Already Friends"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post,:set_comment
  
  def index
    @like = Like.all
  end
    
  def create
    if params[:post_id]
      @like = @post.likes.new
      @like.user_id = current_user.id
      @like.username = current_user.username
    else
      @like = @comment.likes.new
      @like.user_id = current_user.id
      @like.username = current_user.username
    end

    if @like.save
      respond_to do |format|
        format.js
        format.html {redirect_to root_path}
      end
    end  
  end

  def destroy
    @unlike = Like.find_by(id: params[:id])
    if @unlike.destroy
      respond_to do |format|
        format.js
        format.html {redirect_to root_path}
      end
    end
  end
  private
    def set_post
      @post = Post.find_by(id: params[:post_id])
    end

    def set_comment
      @comment = Comment.find_by(id: params[:comment_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    
    
  end

  def new
    @post = Post.new
  end

  def edit
  
  end
  
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption,:post_mode,:file)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	self.per_form_csrf_tokens = true
  def sign_up_params
    params.require(:user).permit(:username,:email,:password,:encrypted_password,:first_name,:last_name,:age,:city )    
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class 
    User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div id="comment<%= comment.id%>">
  <ul class="list-inline">
    <li>
      <h4 style="color: black">
        <%= comment.comment %>
      </h4>
    </li>

    <li>
      <% if comment.likes.where(user_id: current_user.id).exists? %>
        <% @like = comment.likes.where(user_id: current_user.id) %>
        <li id="comment-<%= comment.id %>-like">
        <%= link_to 'Unlike',comment_like_path(comment,@like.ids),data: {toggle:"popover",placement:"top",
        trigger:'hover',content: comment.likes.collect(&:username) }, method: :delete,remote: true%>
        <i class="fa fa-thumbs-o-up"></i>
        </li>

      <% else %>
        <li id="comment-<%= comment.id %>-like">
          <%= link_to 'Like', comment_likes_path(comment),data: {toggle:"popover",placement:"top",
          trigger:'hover',content: comment.likes.collect(&:username) }, method: :post,remote: true%>
          <i class="fa fa-thumbs-o-up"></i>
        </li>
      <% end %>
    </li>

    <li>
      <%=link_to"Delete",post_comment_path(post,comment),method: :delete,remote: true %>
      <i class="fa fa-remove"></i>
    </li>
  </ul>
</div>
<br> 

app/views/comments/_form.html.erb
<%= form_with scope: :comment,url: post_comments_path(post), method: :post,remote: true do |form| %>
  <div class="actions">
    <%= form.text_field :comment,id: 'commenttextfield',placeholder: "Write Comment..",required: true%> 
  </div>
<% end %>

app/views/comments/create.js.erb
$("#commenttextfield").val("") ;
$(".displaycomments<%= @post.id%>").append('<%= j render "/comments/comment", comment: @comment, post: @post.id%>') ;

app/views/comments/destroy.js.erb
$("#comment<%= @comment.id%>").fadeOut(500,function(){
  $(this).remove() ;
});

app/views/friendships/_friends.html.erb
<div class ="panel panel-info" id="friendslist">
  <div class="panel-heading">
    <div class="container-fluid row">
      <div class="col-sm-6">
        <%= friend.friend.first_name %> <%= friend.friend.last_name %>    
      </div>
      <div class="col-sm-6">
        <%= link_to "View Profile" %>      
      </div>
    </div>
  </div>
</div>

app/views/friendships/_list.html.erb
<div class ="panel panel-info">
  <div class="panel-heading">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <%= user.username %>  
        </div>
        <div class="col-sm-6" id="add-friend-<%=user.id%>">
          <%= link_to "Add Friend", friendships_path(friend_id: user.id),method: :post %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <%= user.first_name %>  <%= user.last_name %>
        </div>
        <div class="col-sm-6">
          <%= user.city%>
        </div>
      </div> 
    </div>
  </div>
</div>

app/views/friendships/_pending.html.erb
<div class ="panel panel-info">
  <div class="panel-heading">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <%= req_friends.user.username %>
        </div>
        <div class="col-sm-3">
          <%= link_to "Accept", friendship_path(req_friends), method: :put %>
        </div>
        <div class="col-sm-3">
          <%= link_to "Decline" %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <%= req_friends.user.first_name %> <%= req_friends.user.last_name %>
        </div>
        <div class="col-sm-3">
          <%= req_friends.user.age %> 
        </div>
        <div class="col-sm-3">
          <%= req_friends.user.city %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friendships/create.js.erb
$("#add-friend-<%=friend_id%>").text("Request sent") ;

app/views/friendships/index.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-brand">
        <h2>SocialMedia App</h2>
      </div>
      <ul class="justify-content-center"  style="display: inline-block;">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <h4><%= current_user.username%></h4>
          <button><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></button>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="container-fluid">
  <div class="row" style="background-color: lightblue">
    <h2>Welcome <%= current_user.first_name %> <%= current_user.last_name %></h2>
  </div>
  <br>
  <div class="row" style="background-color: lightgreen">
    <br>
    <div class = "col-sm-6">
      <h4>
        Pending Requests!
      </h4>
    </div>
    <div class="col-sm-6">
      <h4>
        Make New Friends!
      </h4>
      <br>
    </div>
  </div>
  <div class="row">
    
    <div class="col-sm-6">
      <% @pending.each do |req| %>
        <%= render 'friendships/pending', req_friends: req %>
      <% end %>
    </div>
    
    <div class="col-sm-6">
      <% @users.each do |user| %>
        <%= render 'friendships/list', user: user %>
      <% end %>
    </div>
  </div>
</div>

app/views/likes/_like.html.erb
<ul class="list-inline">
  <% if post.likes.where(user_id: current_user.id).exists? %>
    <% @like = post.likes.where(user_id: current_user.id) %>

    <li id="post-<%= post.id %>-like">
    <%= link_to 'Unlike', post_like_path(post,@like.ids), data: {toggle:"popover",placement:"top",
    trigger:'hover',content: post.likes.collect(&:username) }, method: :delete, remote: true %>
    <i class="fa fa-thumbs-up"></i>
    </li>    
  <% else %>   
    <li id="post-<%= post.id %>-like">
    <%= link_to 'Like', post_likes_path(post),data: {toggle:"popover",placement:"top",
    trigger:'hover',content: post.likes.collect(&:username) }, method: :post,remote: true%>
    <i class="fa fa-thumbs-o-up"></i>
    </li>
  <% end %>

  <li>
    <a data-toggle="collapse"href="#comment_<%=post.id%>">Comments</a><i class="fa fa-comments-o"></i>
  </li>
  
  <li><%= link_to'Delete Post',post,method: :delete,data:{ confirm:'Are you sure?'},remote: true%>
    <i class="fa fa-remove"></i>
  </li>
</ul>

app/views/likes/create.js.erb
<% if params[:post_id] %>
  $("#post-<%= @post.id %>-like  a").text("Unlike");
  $("#post-<%= @post.id %>-like i").fadeIn(10,function(){
    $(this).removeClass("fa fa-thumbs-o-up").addClass("fa fa-thumbs-up");
}) ;

<% else %>
  $("#comment-<%= @comment.id%>-like a").text("Unlike");
  $("#comment-<%= @comment.id%>-like i").fadeIn(10,function(){
    $(this).removeClass("fa fa-thumbs-o-up").addClass("fa fa-thumbs-up");
}) ;
<% end %>

app/views/likes/destroy.js.erb
<% if params[:post_id] %>
  $("#post-<%= @post.id %>-like a").text("Like") ;
  $("#post-<%= @post.id %>-like i").fadeIn(10,function(){
    $(this).removeClass("fa fa-thumbs-up").addClass("fa fa-thumbs-o-up");
  });
<% else %>
  $("#comment-<%= @comment.id%>-like a").text("Like");
  $("#comment-<%= @comment.id %>-like i").fadeIn(10,function() {
    $(this).removeClass("fa fa-thumbs-o-up").addClass("fa fa-thumbs-up");
  });
<% end %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @like.each do |like| %>
      <tr>
        <td><%= like.user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button><%= link_to 'Home Page',dashboard_index_path %></button>

app/views/posts/_form.html.erb
<div id = "postform">
  <%= form_with(model: post, remote: true, method: :post) do |form| %>
    <div class="form-group">
      <%= form.label :caption,"Write post"%>
      <%= form.text_field :caption,class: "formtextfield",placeholder: "type here...",required: true %> 
      <br>
    </div>
    <div class ="form-group" required>
      <%= form.radio_button :post_mode,'0',class: "formbutton"%> Public
      <%= form.radio_button :post_mode,'-1',class: "formbutton"%> Private
      <%= form.radio_button :post_mode,'1',class: "formbutton"%> Friends
    </div>
    <div class="form-group">
      <%= form.label :caption,"Attach Photo"%>
      <%= form.file_field :file%>
    </div>
    <br>
    <div class="actions">
      <%= form.submit "Post"%>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class ="panel panel-info" id="post_<%= post.id%>">
  <div class="panel-heading">
    <%= render '/likes/like', post: post %>
  </div>  
  <div class="panel-body">
    <h2 style="color: green">
      <%= post.caption %>
      <% if post.file.attached? %>
        <%= image_tag post.file %>
      <% end %>
    </h2>
    <div id="comment_<%= post.id%>" class="collapse" style="background-color: lightgray">
      <%= render '/comments/form', post: post %>

      <div class="displaycomments<%= post.id%>">
        <% post.comments.each do |comment| %>
          <% id = comment.user_id ; username = User.find(id).username %> <%= username %>
          <%= render '/comments/comment',comment:comment,post: post %>
        <% end %>
      </div>  
    </div>
  </div>
</div >

app/views/posts/create.js.erb
$('.formbutton').val("");
$('.formtextfield').val("");
$("#displaypost").append('<%= j render "/posts/post",post: @post %>') ;

app/views/posts/destroy.js.erb
$("#post_<%= @post.id%>").fadeOut(500,function(){
  $(this).remove();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Like', post_like_index_path(post), method: :post %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= form_with scope: :comment,url: post_comments_path(@post), method: :post,local:true do |form| %>
  <div class="actions">
    <%= form.text_field :comment %> 
  </div>
<% end %>

<table>
  <tr>
    <th>Comment</th>
  </tr>
  <% @post.comments.each do |t| %>
    <tr>
      <td><%= t.comment%></td>
      <td><%= link_to "like", comment_like_index_path(t), method: :post %></td>
      <td><%= link_to "delete", post_comment_path(@post,t), method: :delete %></td>
    </tr>
  <% end %>
</table>


<button><%= link_to 'Back', posts_path %></button>